// Aggregates IToolCatalog instances generated by AcadMcp.SourceGen and exposes them per category.
// Tools' actual invocation handlers are looked up via reflection at call time.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using AcadMcp.Shared.Mcp;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace AcadMcp.Backend.Mcp;

public sealed class ToolRegistry
{
    private readonly ILogger<ToolRegistry> _logger;
    private readonly Dictionary<string, IToolCatalog> _catalogs = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<(string Cat, string Tool), MethodInfo> _methodCache = new();

    public ToolRegistry(ILogger<ToolRegistry> logger)
    {
        _logger = logger;
        DiscoverCatalogs();
    }

    // Parameterless constructor used by unit tests (no DI container / no real logger).
    public ToolRegistry() : this(NullLogger<ToolRegistry>.Instance) { }

    public IReadOnlyCollection<string> Categories => _catalogs.Keys;

    public IReadOnlyList<McpToolMetadata> ToolsFor(string category)
    {
        return _catalogs.TryGetValue(category, out var c) ? c.Tools : Array.Empty<McpToolMetadata>();
    }

    public bool TryGetTool(string category, string toolName, out McpToolMetadata? meta)
    {
        meta = null;
        if (!_catalogs.TryGetValue(category, out var c)) return false;
        meta = c.Tools.FirstOrDefault(t => string.Equals(t.Name, toolName, StringComparison.Ordinal));
        return meta is not null;
    }

    public MethodInfo? ResolveMethod(McpToolMetadata meta)
    {
        var key = (meta.Category, meta.Name);
        if (_methodCache.TryGetValue(key, out var cached)) return cached;

        var asm = Assembly.GetExecutingAssembly();
        var type = asm.GetType(meta.DeclaringTypeFullName)
                   ?? AppDomain.CurrentDomain.GetAssemblies()
                       .Select(a => a.GetType(meta.DeclaringTypeFullName))
                       .FirstOrDefault(t => t is not null);
        var method = type?.GetMethod(meta.MethodName,
            BindingFlags.Public | BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.FlattenHierarchy);
        if (method is null)
        {
            _logger.LogWarning("Could not resolve tool method {Type}.{Method}",
                meta.DeclaringTypeFullName, meta.MethodName);
            return null;
        }
        _methodCache[key] = method;
        return method;
    }

    private void DiscoverCatalogs()
    {
        var iface = typeof(IToolCatalog);
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type[] types;
            try { types = asm.GetTypes(); }
            catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t is not null).Cast<Type>().ToArray(); }

            foreach (var t in types)
            {
                if (t.IsAbstract || t.IsInterface) continue;
                if (!iface.IsAssignableFrom(t)) continue;
                if (t.GetConstructor(Type.EmptyTypes) is null) continue;
                try
                {
                    var instance = (IToolCatalog)Activator.CreateInstance(t)!;
                    _catalogs[instance.Category] = instance;
                    _logger.LogInformation("Loaded catalog {Category} with {Count} tools",
                        instance.Category, instance.Tools.Count);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to instantiate catalog {Type}", t.FullName);
                }
            }
        }
    }
}
