<#
.SYNOPSIS
    Generates a new acad-<name> MCP category: stub C# folder, manifest, launcher, smoke test.
    Single source of truth for category scaffolding (see rule 41-new-category-flow.md).

.DESCRIPTION
    Creates EVERYTHING needed for a new MCP category in a uniform layout that
    check-manifests.ps1 can validate:

      src/AcadMcp.Backend/Categories/<Folder>/<Folder>Tools.cs   (stub [McpTool])
      src/AcadMcp.Backend/Categories/<Folder>/_README.md         (planned tool list)
      toolbank-manifests/acad-<name>.json                          (manifest with placeholders)
      bin-launchers/acad-<name>.cmd                               (Release exe launcher)
      tests/AcadMcp.Tests/Categories/<Folder>Tests.cs             (smoke test stub)

    Idempotent: refuses to overwrite by default. Use -Force to wipe and regenerate.

.PARAMETER Name
    kebab-case category name (matches launcher arg, manifest id suffix). Required.
    Example: "geometry-2d", "annotations", "architecture"

.PARAMETER DisplayName
    Human-readable category title. Defaults to Title Cased Name.

.PARAMETER Description
    One-paragraph description (will land in toolbank manifest "description" field).
    If omitted, a placeholder is inserted with a TODO marker.

.PARAMETER Tags
    Optional array of tags. Defaults include "autocad" + the name itself.

.PARAMETER RepoRoot
    Repository root. Defaults to parent of script directory.

.PARAMETER Force
    Overwrite existing files for the category.

.EXAMPLE
    pwsh scripts/new-category.ps1 -Name geometry-2d -DisplayName "AutoCAD 2D Geometry" `
         -Description "Create and edit 2D geometry: lines, circles, arcs, polylines, splines."

.EXAMPLE
    pwsh scripts/new-category.ps1 -Name annotations -Force
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Name,
    [string]$DisplayName,
    [string]$Description,
    [string[]]$Tags,
    [string]$RepoRoot,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

if ($Name -notmatch '^[a-z][a-z0-9]*(-[a-z0-9]+)*$') {
    Write-Error "Name must be kebab-case starting with a letter, e.g. 'geometry-2d'. Got: '$Name'"
    exit 2
}

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $scriptDir = if ($PSScriptRoot) { $PSScriptRoot }
                 elseif ($MyInvocation.MyCommand.Path) { Split-Path -Parent $MyInvocation.MyCommand.Path }
                 else { (Get-Location).Path }
    $RepoRoot = Split-Path -Parent $scriptDir
}

# Naming map (rule 41 single source of truth)
$nameKebab   = $Name.ToLower()
$folderName  = ($nameKebab -split '-' | ForEach-Object {
    if ($_ -match '^\d') { $_ } else { $_.Substring(0,1).ToUpper() + $_.Substring(1) }
}) -join ''
$manifestId  = "acad-$nameKebab"
$nsName      = "AcadMcp.Backend.Categories.$folderName"
$className   = "${folderName}Tools"
$displayName = if ([string]::IsNullOrWhiteSpace($DisplayName)) {
    "AutoCAD " + (((($nameKebab -split '-') | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) })) -join " ")
} else { $DisplayName }
$descBody    = if ([string]::IsNullOrWhiteSpace($Description)) {
    "TODO: replace - one-paragraph description of the $manifestId category. Lists what kinds of operations live here, which AutoCAD APIs they wrap, and any plugin/COM constraints."
} else { $Description }
$tagsFinal = @("autocad", "cad", "dwg", $nameKebab) + (@() + $Tags) | Select-Object -Unique

# Paths
$catDir       = Join-Path $RepoRoot "src\AcadMcp.Backend\Categories\$folderName"
$catCs        = Join-Path $catDir "$className.cs"
$catReadme    = Join-Path $catDir "_README.md"
$manifestPath = Join-Path $RepoRoot "toolbank-manifests\$manifestId.json"
$launcherDir  = Join-Path $RepoRoot "bin-launchers"
$launcherPath = Join-Path $launcherDir "$manifestId.cmd"
$testsDir     = Join-Path $RepoRoot "tests\AcadMcp.Tests\Categories"
$testPath     = Join-Path $testsDir "${folderName}Tests.cs"

$existing = @($catDir, $manifestPath, $launcherPath, $testPath) | Where-Object { Test-Path $_ }
if ($existing.Count -gt 0 -and -not $Force) {
    Write-Host "These targets already exist:" -ForegroundColor Yellow
    $existing | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    Write-Error "Refusing to overwrite without -Force."
    exit 3
}

Write-Host "=== new-category $manifestId ===" -ForegroundColor Cyan
Write-Host "Folder      : $folderName" -ForegroundColor DarkGray
Write-Host "Namespace   : $nsName" -ForegroundColor DarkGray
Write-Host "Manifest id : $manifestId" -ForegroundColor DarkGray
Write-Host ""

# 1. Category folder + stub tool
if (-not (Test-Path $catDir)) { New-Item -ItemType Directory -Path $catDir -Force | Out-Null }

$toolName = ($nameKebab -replace '-', '_') + "_placeholder"
$stubCs = @"
// Stub category for $manifestId.
// Generated by scripts/new-category.ps1. Replace the placeholder tool with real
// implementations and re-run: dotnet AcadMcp.Backend --category $nameKebab --regenerate-manifest

using AcadMcp.Shared.Mcp;

namespace $nsName;

public static class $className
{
    public sealed record PlaceholderArgs(string Echo);
    public sealed record PlaceholderResult(string Echo, string Category);

    [McpTool(
        "$toolName",
        "Placeholder tool for the $manifestId category. Echoes its input. Replace with real tools before phase end.",
        "$nameKebab",
        Intent = new[]
        {
            "test connection to $nameKebab",
            "ping $nameKebab category",
            "is $nameKebab loaded",
            "sprawdz polaczenie z $nameKebab",
            "test kategorii $nameKebab"
        },
        ReadOnly = true,
        RequiresPlugin = false)]
    public static PlaceholderResult Placeholder(PlaceholderArgs args)
    {
        return new PlaceholderResult(args.Echo, "$nameKebab");
    }
}
"@
Set-Content -Path $catCs -Value $stubCs -Encoding UTF8
Write-Host "  wrote $($catCs.Substring($RepoRoot.Length+1))" -ForegroundColor Green

# 2. README with planned tools
$readme = @"
# $displayName  ($manifestId)

$descBody

## Planned tools

> Replace this list with real entries as you implement them. Each item becomes one ``[McpTool]`` static method in ``$className.cs``.

- [ ] TODO_first_tool   - one-line purpose
- [ ] TODO_second_tool  - one-line purpose
- [ ] TODO_third_tool   - one-line purpose

## Conventions for this category

- All tools live in ``$className.cs`` (or split per concern: ``${folderName}Lines.cs``, ``${folderName}Curves.cs``, ...)
- Every tool MUST follow rules 20-25 (``[McpTool]`` shape, naming, args/results, idempotency, category binding, tests)
- ``Category = "$nameKebab"`` on every tool; the source generator validates this matches the folder

## How to regenerate the manifest from code

``dotnet run --project src/AcadMcp.Backend -- --category $nameKebab --regenerate-manifest``
"@
Set-Content -Path $catReadme -Value $readme -Encoding UTF8
Write-Host "  wrote $($catReadme.Substring($RepoRoot.Length+1))" -ForegroundColor Green

# 3. Manifest with placeholders (5 PL+EN intent_examples to satisfy rule 31)
$manifest = [PSCustomObject]@{
    id          = $manifestId
    name        = $manifestId
    description = $descBody
    transport   = [PSCustomObject]@{
        type    = "stdio"
        command = $launcherPath -replace '/', '\'
        args    = @()
        env     = [PSCustomObject]@{}
    }
    lazy_mode      = $true
    tags           = $tagsFinal
    # intent_examples are auto-populated by BankAutoRegister from the [McpTool] Intent= arrays.
    # The first --regenerate-manifest call after adding real tools will fill this in.
    intent_examples = @()
    tools_summary = @(
        [PSCustomObject]@{
            name        = $toolName
            description = "Placeholder tool generated by new-category.ps1. Replace before phase ends."
            tags        = @("placeholder", "stub")
        }
    )
    metadata = [PSCustomObject]@{
        category                = $nameKebab
        tool_count_target       = 0
        requires_plugin         = $true
        supported_acad_versions = @("2020","2021","2022","2023","2024","2025")
        supported_lt            = $false
        owner                   = "AutoCAD MCP Megasystem"
        version                 = "0.1.0"
        phase                   = "scaffolded"
    }
}
if (-not (Test-Path (Split-Path -Parent $manifestPath))) {
    New-Item -ItemType Directory -Path (Split-Path -Parent $manifestPath) -Force | Out-Null
}
$manifest | ConvertTo-Json -Depth 20 | Set-Content -Path $manifestPath -Encoding UTF8
Write-Host "  wrote $($manifestPath.Substring($RepoRoot.Length+1))" -ForegroundColor Green

# 4. Launcher
if (-not (Test-Path $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
$launcher = @"
@echo off
REM Launcher for $manifestId. Generated by scripts/new-category.ps1.
REM The exe path is resolved relative to repo root; override with %ACADMCP_BACKEND_EXE%.
setlocal
if defined ACADMCP_BACKEND_EXE (
    set "EXE=%ACADMCP_BACKEND_EXE%"
) else (
    set "EXE=%~dp0..\src\AcadMcp.Backend\bin\Release\net8.0\AcadMcp.Backend.exe"
)
"%EXE%" --category $nameKebab %*
"@
Set-Content -Path $launcherPath -Value $launcher -Encoding ASCII
Write-Host "  wrote $($launcherPath.Substring($RepoRoot.Length+1))" -ForegroundColor Green

# 5. Smoke test stub
if (-not (Test-Path $testsDir)) { New-Item -ItemType Directory -Path $testsDir -Force | Out-Null }
$test = @"
// Smoke test for $manifestId category.
// Generated by scripts/new-category.ps1. Asserts the source generator wired the
// stub tool into the catalog. Replace as real tools land.

using AcadMcp.Backend.Mcp;
using AcadMcp.Shared.Mcp;
using Xunit;

namespace AcadMcp.Tests.Categories;

public class ${folderName}Tests
{
    [Fact]
    public void Catalog_contains_at_least_one_tool_for_$($folderName.ToLower())()
    {
        var registry = new ToolRegistry();
        var tools = registry.ToolsFor("$nameKebab");
        Assert.NotEmpty(tools);
    }
}
"@
Set-Content -Path $testPath -Value $test -Encoding UTF8
Write-Host "  wrote $($testPath.Substring($RepoRoot.Length+1))" -ForegroundColor Green

Write-Host ""
Write-Host "=== Done. Next steps ===" -ForegroundColor Cyan
Write-Host "  1. Build:    dotnet build src/AcadMcp.sln -c Release" -ForegroundColor White
Write-Host "  2. Validate: pwsh scripts/check-manifests.ps1" -ForegroundColor White
Write-Host "  3. Replace TODO placeholders in:" -ForegroundColor White
Write-Host "       - $($manifestPath.Substring($RepoRoot.Length+1)) (intent_examples, description)" -ForegroundColor DarkGray
Write-Host "       - $($catCs.Substring($RepoRoot.Length+1)) (real [McpTool] methods)" -ForegroundColor DarkGray
Write-Host "  4. Regenerate manifest after adding tools:" -ForegroundColor White
Write-Host "       dotnet run --project src/AcadMcp.Backend -- --category $nameKebab --regenerate-manifest" -ForegroundColor DarkGray
Write-Host "  5. Register with ToolBank:" -ForegroundColor White
Write-Host "       pwsh scripts/register-mcps.ps1" -ForegroundColor DarkGray
exit 0
