<#
.SYNOPSIS
    Ensures every MCP category has a launcher script in bin-launchers/.

.DESCRIPTION
    The README's Quickstart has always told you to run this, but the script did not
    exist - the launchers in bin-launchers/ were generated once by new-category.ps1
    and committed. This restores the documented step.

    It deliberately does NOT regenerate everything. Several launchers are hand-tuned
    and regenerating them would silently destroy that:

      * acad-router.cmd  invokes `dotnet <dll>` rather than the .exe directly
      * acad-vision.cmd  starts the Python sidecar (start-vision.ps1 -EnsureRunning
                         -WaitHealthy) before the .NET host, so the HTTP API is
                         reachable when the first vision tool fires

    So: one launcher per manifest in mcpbank-manifests/, missing ones created from
    the standard template, existing ones left alone unless you pass -Force.

.PARAMETER RepoRoot
    Repository root. Defaults to the parent of this script's directory.

.PARAMETER Force
    Overwrite launchers that already exist. Refuses to touch the two hand-tuned ones
    above unless you also pass -IncludeSpecial.

.PARAMETER IncludeSpecial
    With -Force, also overwrite acad-router.cmd and acad-vision.cmd. You almost
    certainly do not want this.

.PARAMETER DryRun
    Report what would change without writing anything.

.EXAMPLE
    pwsh scripts/package.ps1

.EXAMPLE
    pwsh scripts/package.ps1 -DryRun
#>
[CmdletBinding()]
param(
    [string]$RepoRoot,
    [switch]$Force,
    [switch]$IncludeSpecial,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $RepoRoot = Split-Path -Parent $scriptDir
}

$manifestDir = Join-Path $RepoRoot "mcpbank-manifests"
$launcherDir = Join-Path $RepoRoot "bin-launchers"

if (-not (Test-Path $manifestDir)) {
    Write-Error "Manifest directory not found: $manifestDir"
    exit 2
}
if (-not (Test-Path $launcherDir)) {
    if (-not $DryRun) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
    Write-Host "Created $launcherDir" -ForegroundColor DarkGray
}

# Hand-tuned launchers that the standard template would break. See the .DESCRIPTION.
$special = @("acad-router", "acad-vision")

# CRLF throughout: CMD.EXE mis-parses labels and goto targets in batch files saved
# with LF endings. .gitattributes pins *.cmd to eol=crlf for the same reason.
function New-LauncherText([string]$category) {
    $lines = @(
        '@echo off'
        "REM Launcher for acad-$category. Generated by scripts/package.ps1."
        'REM The exe path is resolved relative to repo root; override with %ACADMCP_BACKEND_EXE%.'
        'setlocal'
        'if defined ACADMCP_BACKEND_EXE ('
        '    set "EXE=%ACADMCP_BACKEND_EXE%"'
        ') else ('
        '    set "EXE=%~dp0..\src\AcadMcp.Backend\bin\Release\net8.0\AcadMcp.Backend.exe"'
        ')'
        "`"%EXE%`" --category $category %*"
    )
    return ($lines -join "`r`n") + "`r`n"
}

$created = New-Object System.Collections.Generic.List[string]
$updated = New-Object System.Collections.Generic.List[string]
$skipped = New-Object System.Collections.Generic.List[string]
$kept    = New-Object System.Collections.Generic.List[string]

$manifests = Get-ChildItem -Path $manifestDir -Filter "acad-*.json" | Sort-Object Name

foreach ($m in $manifests) {
    $id = [System.IO.Path]::GetFileNameWithoutExtension($m.Name)   # e.g. acad-geometry-2d
    $category = $id -replace '^acad-', ''                          # e.g. geometry-2d
    $target = Join-Path $launcherDir "$id.cmd"
    $exists = Test-Path $target
    $isSpecial = $special -contains $id

    if ($exists -and -not $Force) {
        $kept.Add($id); continue
    }
    if ($exists -and $Force -and $isSpecial -and -not $IncludeSpecial) {
        $skipped.Add($id); continue
    }

    if (-not $DryRun) {
        [System.IO.File]::WriteAllText($target, (New-LauncherText $category), [System.Text.UTF8Encoding]::new($false))
    }
    if ($exists) { $updated.Add($id) } else { $created.Add($id) }
}

# A launcher with no matching manifest is dead weight - MCP Nexus discovers categories
# through the manifests, so nothing would ever route to it.
$manifestIds = $manifests | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
$orphans = Get-ChildItem -Path $launcherDir -Filter "acad-*.cmd" -ErrorAction SilentlyContinue |
    ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) } |
    Where-Object { $manifestIds -notcontains $_ }

Write-Host ""
Write-Host "=== package ===" -ForegroundColor Cyan
Write-Host ("  Manifests        : {0}" -f $manifests.Count)
Write-Host ("  Launchers created: {0}{1}" -f $created.Count, $(if ($created.Count) { " -> " + ($created -join ", ") } else { "" })) -ForegroundColor $(if ($created.Count) { "Green" } else { "DarkGray" })
Write-Host ("  Launchers updated: {0}{1}" -f $updated.Count, $(if ($updated.Count) { " -> " + ($updated -join ", ") } else { "" })) -ForegroundColor $(if ($updated.Count) { "Yellow" } else { "DarkGray" })
Write-Host ("  Left as-is       : {0}" -f $kept.Count) -ForegroundColor DarkGray
if ($skipped.Count) {
    Write-Host ("  Hand-tuned, not overwritten: {0} (pass -IncludeSpecial to force)" -f ($skipped -join ", ")) -ForegroundColor Yellow
}
if ($orphans) {
    Write-Host ("  WARNING - launcher without a manifest: {0}" -f ($orphans -join ", ")) -ForegroundColor Red
    Write-Host "  Nothing will ever route to these: MCP Nexus discovers categories via manifests." -ForegroundColor Red
}
if ($DryRun) { Write-Host "  (dry run - nothing written)" -ForegroundColor Cyan }
Write-Host ""

if ($orphans) { exit 1 }
exit 0
