# -*- coding: utf-8 -*-
"""Live verification for acad-underlays.attach_pdf_underlay (2026-08-11, second underlays pass).

PdfReference/PdfDefinition were confirmed, via a zero-cost compiler probe, to mirror the
DgnReference/DwfReference shape exactly - same AttachUnderlay<TDef,TRef> generic path already
proven by attach_dwf_underlay, one more branch on DictKeyFor/KindOf. The first underlays tranche
withheld this tool for lack of a PDF to test against, not an API problem.

The fixture (scripts/fixtures/pdf-underlay-test/sample.pdf) is generated by this bank's OWN
already-verified files.export_file - never a personal document off the machine. The drawing
exported was a 300x100 rectangle with a circle near one corner, deliberately non-square (rule 26
section 14) - but MEASURED live: the exporter fits the drawing onto a default page rather than
cropping to content, so the PDF's actual MediaBox is a standard 612x792 (US Letter portrait,
ratio 0.773), not the drawing's own 3:1. Still non-square, still enough to catch a width/height
swap (which would report ~1.29 instead) - this script reads the real MediaBox straight out of
the PDF bytes at runtime rather than assuming a ratio, so the ground truth travels with the
fixture instead of being hardcoded against an assumption that turned out wrong once already.

Controls, matching the pattern already proven in verify-underlays.py:
  * a missing file and a missing path are refused before touching AutoCAD
  * attaching under a name already used by a different file is refused
  * the SAME file/name attached twice reuses the definition (reusedDefinition: true), and
    detach_underlay's "survives the first removal, dies on the last" branch is exercised
  * kind is reported as "pdf" specifically, not just "attached successfully"
  * the reported width:height ratio is checked against the PDF's own real MediaBox, read
    independently out of the file bytes - a swapped width/height would fail this
  * clip_underlay is exercised on the PDF underlay with an isolation check against a second,
    untouched underlay - proving the shared generic code path also works for this third type
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))  # scripts/mcpcall.py
from mcpcall import Session  # noqa: E402

S = {c: Session(c) for c in ("files", "underlays")}
results = []

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
PDF = os.path.join(SCRIPTS_DIR, "fixtures", "pdf-underlay-test", "sample.pdf")


def read_media_box_ratio(pdf_path):
    """Ground truth read directly from the PDF bytes - independent of anything AutoCAD reports."""
    data = open(pdf_path, "rb").read()
    m = re.search(rb"/MediaBox\s*\[\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\]", data)
    if not m:
        raise SystemExit(f"Could not find /MediaBox in {pdf_path}")
    x0, y0, x1, y1 = (float(v) for v in m.groups())
    w, h = x1 - x0, y1 - y0
    return w / h if h else 0


def do(cat, tool, args, label=None, expect_fail=False):
    ok, r = S[cat].call(tool, args)
    label = label or tool
    missing = "UnknownTool" in str(r) or "not found in category" in str(r)
    good = False if missing else ((not ok) if expect_fail else ok)
    results.append((label, good))
    detail = "" if good else f"  -> {str(r)[:260]}"
    if missing:
        detail = f"  -> TOOL NOT REGISTERED: {str(r)[:150]}"
    elif expect_fail and not ok:
        detail = f"  (refused as intended: {str(r)[-140:]})"
    print(f"  {'OK  ' if good else 'FAIL'} {label}{detail}")
    return r


def check(label, condition, detail=""):
    results.append((label, bool(condition)))
    print(f"  {'OK  ' if condition else 'FAIL'} {label}" + ("" if condition else f"  -> {detail}"))


if not os.path.exists(PDF):
    raise SystemExit(f"Expected test fixture missing: {PDF}")

print("== fresh drawing, cross-session probe (rule 26 section 13a) ==")
do("files", "new_document", {})
ok, r = S["files"].call("list_documents", {})
if not ok:
    raise SystemExit(f"AutoCAD not reachable: {r}")
for d in (r.get("documents") or [])[:-1]:
    S["files"].call("close_document", {"path": d.get("path") or d.get("name"), "save": False})

print("\n== attach_pdf_underlay: refusals that never touch AutoCAD ==")
do("underlays", "attach_pdf_underlay",
   {"path": "C:\\does\\not\\exist.pdf", "insertionPoint": {"x": 0, "y": 0, "z": 0}},
   label="a missing file is refused", expect_fail=True)
do("underlays", "attach_pdf_underlay", {"insertionPoint": {"x": 0, "y": 0, "z": 0}},
   label="a missing path argument is refused", expect_fail=True)

print("\n== attach_pdf_underlay: the fixture, and kind is reported as pdf ==")
r1 = do("underlays", "attach_pdf_underlay",
        {"path": PDF, "insertionPoint": {"x": 0, "y": 0, "z": 0}, "name": "sample1"})
h1 = None
if isinstance(r1, dict):
    u1 = r1.get("underlay") or {}
    h1 = u1.get("handle")
    check("PROVEN kind is reported as pdf, not dgn/dwf", u1.get("kind") == "pdf", str(u1)[:200])
    check("reusedDefinition is false for the first placement", r1.get("reusedDefinition") is False,
          str(r1)[:200])

print("\n== attach_pdf_underlay again: SAME file, SAME name - must REUSE the definition ==")
h2 = None
if h1:
    r2 = do("underlays", "attach_pdf_underlay",
            {"path": PDF, "insertionPoint": {"x": 500, "y": 0, "z": 0}, "name": "sample1"})
    if isinstance(r2, dict):
        h2 = (r2.get("underlay") or {}).get("handle")
        check("PROVEN the definition was REUSED, not duplicated", r2.get("reusedDefinition") is True,
              str(r2)[:200])
    if h1 and h2:
        check("the two placements sharing a definition have different handles", h1 != h2,
              f"h1={h1} h2={h2}")

do("underlays", "attach_pdf_underlay",
   {"path": "C:\\does\\not\\exist.pdf", "insertionPoint": {"x": 999, "y": 999, "z": 0}, "name": "sample1"},
   label="the same name against a DIFFERENT (non-existent) file is refused", expect_fail=True)

print("\n== list_underlays: the PDF placements are enumerated with the right aspect ==")
r = do("underlays", "list_underlays", {})
if isinstance(r, dict):
    u1now = next((i for i in (r.get("underlays") or []) if i.get("handle") == h1), None)
    check("PROVEN list_underlays enumerates both PDF placements",
          r.get("count") == len([x for x in (h1, h2) if x]), f"count={r.get('count')}")
    if u1now:
        expected_ratio = read_media_box_ratio(PDF)
        ext = u1now.get("extents") or {}
        mn, mx = ext.get("min") or {}, ext.get("max") or {}
        w = (mx.get("x", 0) - mn.get("x", 0))
        h = (mx.get("y", 0) - mn.get("y", 0))
        ratio = (w / h) if h else 0
        check(f"PROVEN the underlay's drawing-space aspect ratio ({ratio:.3f}) matches the PDF's "
              f"own real MediaBox ({expected_ratio:.3f}), read independently out of the file bytes",
              abs(ratio - expected_ratio) < 0.05, f"extents={ext}")

print("\n== clip_underlay on the PDF underlay, isolation against a second untouched one ==")
if h1 and h2:
    do("underlays", "clip_underlay", {"handle": h1, "points": [{"x": 0, "y": 0}]},
       label="a single clip point is refused", expect_fail=True)

    r = do("underlays", "clip_underlay", {
        "handle": h1,
        "points": [{"x": 0, "y": 0}, {"x": 1, "y": 1}],
    }, label="clip to a small rectangle near the origin of local space")
    if isinstance(r, dict):
        check("clipped is true and the local bounds are reported",
              r.get("clipped") is True and r.get("underlayWidth") is not None
              and r.get("underlayHeight") is not None, str(r)[:300])
        ea = r.get("extentsAfter") or {}
        eb = r.get("extentsBefore") or {}
        spanX_after = (ea.get("max") or {}).get("x", 0) - (ea.get("min") or {}).get("x", 0)
        spanX_before = (eb.get("max") or {}).get("x", 0) - (eb.get("min") or {}).get("x", 0)
        check("PROVEN clipping shrank the drawing-space extents",
              spanX_after < spanX_before, f"before={spanX_before} after={spanX_after}")

    r = do("underlays", "list_underlays", {})
    if isinstance(r, dict):
        u2now = next((i for i in (r.get("underlays") or []) if i.get("handle") == h2), None)
        check("PROVEN a DIFFERENT PDF placement (h2) was untouched by clipping h1",
              u2now is not None and u2now.get("clipped") is False, str(u2now)[:250])

print("\n== detach_underlay: the shared PDF definition ==")
if h1 and h2:
    r = do("underlays", "detach_underlay", {"handle": h1})
    if isinstance(r, dict):
        check("PROVEN the definition SURVIVED - h2 still uses it", r.get("defRemoved") is False,
              str(r)[:200])
    r = do("underlays", "detach_underlay", {"handle": h2})
    if isinstance(r, dict):
        check("PROVEN the definition was removed on the LAST placement", r.get("defRemoved") is True,
              str(r)[:200])
    do("underlays", "detach_underlay", {"handle": h2},
       label="detaching an already-erased handle is refused", expect_fail=True)

passed = sum(1 for _, ok in results if ok)
print(f"\n==== {passed}/{len(results)} checks passed ====")
for label, ok in results:
    if not ok:
        print(f"  FAILED: {label}")
raise SystemExit(0 if passed == len(results) else 1)
