// Smoke test for acad-plumbing category.
// Generated by scripts/new-category.ps1. Asserts the source generator wired the
// stub tool into the catalog. Replace as real tools land.

using AcadMcp.Backend.Mcp;
using AcadMcp.Shared.Mcp;
using Xunit;

namespace AcadMcp.Tests.Categories;

public class PlumbingTests
{
    [Fact]
    public void Catalog_contains_at_least_one_tool_for_plumbing()
    {
        var registry = new ToolRegistry();
        var tools = registry.ToolsFor("plumbing");
        Assert.NotEmpty(tools);
    }
}
