@echo off
REM Launcher for acad-schedules. Generated by scripts/new-category.ps1.
REM The exe path is resolved relative to repo root; override with %ACADMCP_BACKEND_EXE%.
setlocal
if defined ACADMCP_BACKEND_EXE (
    set "EXE=%ACADMCP_BACKEND_EXE%"
) else (
    set "EXE=%~dp0..\src\AcadMcp.Backend\bin\Release\net8.0\AcadMcp.Backend.exe"
)
"%EXE%" --category schedules %*
